site_name: My Machine Chodící Větrák
site_description: Dokumentace k projektu MyMachine - Chodící Větrák

repo_name: BrnoMarsRover/myMachine-Fan
repo_url: https://github.com/BrnoMarsRover/myMachine-Fan
edit_uri: edit/main/docs/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Dětský Vynález: big_picture.md
  - Komponenty:
      - Nákupní seznam: construction/komponenty.md
      - Rozborka větráku: construction/rozborka.md
  - Hardware:
      - Schéma: hardware/pinout.md
  - Software:
      - ESP32 program: software/sw.md